# Generated by Django 2.2.7 on 2019-12-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ratting', models.IntegerField()),
                ('date', models.DateField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
    ]
